### PR TITLE
Completed first Upload

### PR DESCRIPTION
**Pull request by maccer989**
Completed first Upload

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@maccer989 
Hey there! Could you please have a look at these: 
**1st query:** Most recent should be first
image

**2nd query**: Last 3 in alphabetical order are: 
image

**4th query** first and last in DATE order
image

**Comment by maccer989** [comment]
Hello I have rerun my quires and checked them off against the code submitted and they produce the following:
Query1
image
Query2
image
Query3
image
Query4
image

**Comment by TheCSharpAcademy** [comment]
> Hello I have rerun my quires and checked them off against the code submitted and they produce the following: Query1 image Query2 image Query3 image Query4 image

Query 1 should be most recent first. 😊

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
Query 1 should be most recent first. 😊
Query 2 should be alphabetical order of events, as it wouldn't make sense to word it alphabetical for numbers.
Query 3 should be first two and last two in date order, not in ID order.

The pictures in my previous comment contain the expected output

**Comment by TheCSharpAcademy** [comment]
@maccer989 Let me know if you need more clarifications 😊

**Comment by TheCSharpAcademy** [comment]
@maccer989 Closing the PR for admin purposes but feel free to reopen when you're ready 😎

**Pull request closed without merging**
